modLoader="javafml"
loaderVersion="[35,)"
issueTrackerURL="https://github.com/ShyNieke/StatuesMod/issues"
license="MIT"

[[mods]]
modId="statues"
version="${file.jarVersion}"
displayName="Statues Mod"
displayURL="https://minecraft.curseforge.com/projects/statues"
authors="ShyNieke, Mrbysco"
description='''
Just a little functional decoration.
'''