modLoader="javafml"
loaderVersion="[45,)"
issueTrackerURL="https://github.com/ShyNieke/StatuesMod/issues"
license="MIT"

[[mods]]
modId="statues"
version="${file.jarVersion}"
displayName="Statues Mod"
displayURL="https://minecraft.curseforge.com/projects/statues"
authors="ShyNieke, Mrbysco"
description='''
Just a little functional decoration.
'''
[[dependencies.statues]]
modId="minecraft"
mandatory=true
versionRange="[1.19.3,1.20)"
ordering="NONE"
side="BOTH"
[[dependencies.statues]]
modId="forge"
mandatory=true
versionRange="[45.1.0,)"
ordering="NONE"
side="BOTH"
[[dependencies.statues]]
modId="curios"
mandatory=false
versionRange="[1.19.4-5.1.5.3,)"
ordering="NONE"
side="BOTH"