modLoader="javafml"
loaderVersion="[46,)"
issueTrackerURL="https://github.com/ShyNieke/StatuesMod/issues"
license="MIT"

[[mods]]
modId="statues"
version="${file.jarVersion}"
displayName="Statues Mod"
displayURL="https://minecraft.curseforge.com/projects/statues"
authors="ShyNieke, Mrbysco"
description='''
Just a little functional decoration.
'''
[[dependencies.statues]]
modId="minecraft"
mandatory=true
versionRange="[1.20,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.statues]]
modId="forge"
mandatory=true
versionRange="[46.0.1,)"
ordering="NONE"
side="BOTH"