modLoader="javafml"
loaderVersion="[25,)"
issueTrackerURL="https://github.com/svennieke/StatuesMod/issues"

[[mods]]
modId="statues"
version="${file.jarVersion}"
displayName="Statues Mod"
displayURL="https://minecraft.curseforge.com/projects/statues"
authors="svennieke"
description='''
Just a little functional decoration.
'''

[[dependencies.statues]]
modId="forge"
mandatory=true
versionRange="[25,)"
ordering="NONE"
side="BOTH"

[[dependencies.statues]]
modId="minecraft"
mandatory=true
versionRange="[1.13.2]"
ordering="NONE"
side="BOTH"